on:
  schedule:
    - cron: '0 20 * * *'
on : workflow_dispatch
    
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup PYTHON
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - uses: browser-actions/setup-edge@v1

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Run Python code
      run: python actualizar_productos.py

    - name: Commit Changes
      run: |
          git config --global user.name 'Victorsitou'
          git config --global user.email '67214928+Victorsitou@users.noreply.github.com'
          git push
          git add .
          git commit -m "Actualizar productos"
          git push